name: cron_test

on:
    schedule:
        -   cron: '0 0 * * 0' # “At 00:00 on Sunday.”

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v3
            -   uses: actions/setup-java@v3
                with:
                    java-version: 11
            -   uses: gradle/gradle-build-action@v2
                with:
                    gradle-version: current
                    arguments: clean cleanTest test
